version: '3.8'

services:
  books-api:
    build: ./
    command: ./books-webAPI
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
          - POSTGRES_PASSWORD=PASSWORD
    ports:
      - 5432:5432